spring:
#  profiles:
#    active: @spring.profiles.active@
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: ${HIBERNATE_DIALECT}
        format_sql: true
        id:
          new_generator_mappings: false
    open-in-view: false

server:
  servlet:
    context-path: /api-v2
  port: ${PORT}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${EXPIRE-LENGTH}

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
