POST 127.0.0.1:{{PORT}}/{{BASE_API}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "firstName": "a",
  "lastName": "c",
  "password": "password"
}

### User login

POST 127.0.0.1:{{PORT}}/{{BASE_API}}/users/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

### User info

GET 127.0.0.1:{{PORT}}/{{BASE_API}}/users/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJleHAiOjE2MjEzODUyODJ9.S-EF3SC185GrSqSUZvv7rb7TcAyKBhK1RvB128fjfJeKuyjM9J1GqS5E38_xd_PE_E1oFfoWOsmioGEl19PbRQ


### Customers Actions
GET 127.0.0.1:{{PORT}}/{{BASE_API}}/clients/list?page=1&limit=20&type=QT&sort=+id&status=active&name=name
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJleHAiOjE2MjE3NzYzNjR9.bssDOm62-iGvlFWXgIoVaJ5kV0ShcIyKp03r1cM1nwPsGr7nla0ELJI10SCB9Zp6D-ZWoGkBHwz4Kynaoj_Omw

